In [1]:
import numpy as np


In [2]:
a = np.array([[1, 2]])

In [3]:
a.shape

(1, 2)

In [4]:
a.ndim

2

In [5]:
b = np.array([3, 4])

In [6]:
b.shape


(2,)

In [7]:
b.ndim

1

In [8]:
c1 = np.linspace(3, 7, num=5)  

In [9]:
c1

array([3., 4., 5., 6., 7.])

In [10]:
d = np.array([[1, 2],[3, 4]])

In [11]:
d.ndim

2

In [12]:
d.shape

(2, 2)

In [13]:
e = np.array([[[1, 2],[3, 4]]])

In [14]:
e.ndim

3

In [15]:
e.shape

(1, 2, 2)

In [16]:
f =np.array([[[[1, 2],[3, 4]]]])

In [17]:
f.shape


(1, 1, 2, 2)

In [19]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np.where(a % 2 == 0)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 2, 0, 2, 0, 2], dtype=int64))