In [1]:
import pandas as pd
import numpy as np



In [2]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [3]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [6]:
x = np.arange(4)
x
xx = x.reshape(4,1)
xx
# y = np.ones(5)
# z = np.ones((3,4))

array([[0],
       [1],
       [2],
       [3]])

In [10]:
y = np.ones(5)
y
z = np.ones((3,4))
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [12]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [13]:
x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [14]:
xx = x.reshape(4,1)
xx

array([[0],
       [1],
       [2],
       [3]])

In [15]:
xx.shape

(4, 1)

In [16]:
y.shape

(5,)

In [17]:
(xx + y).shape

(4, 5)

In [18]:
xx+y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])